feature/manage-sell
iExecBlockchainComputing/dataprotector-sdk pull request #130
Opened 2024-01-22 08:28 UTC by Le-Caignec

2024-01-22 10:06 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Sale.sol
> +    }
we should check
- the data is not available for renting or subscription
- there is no pending rental or subscription on the data

2024-01-22 10:19 UTC, Le-Caignec commented on packages/sharing-smart-contract/contracts/modules/Collection.sol
> +    }
enable ProtectedDataSharing contract to change protectedData from one mapping to an other one
Commit: 7a9763727a83350c7ce4a38bdfc2ae17375db535

2024-01-22 10:20 UTC, Le-Caignec commented on packages/sharing-smart-contract/contracts/Store.sol
> +    }
Commit: 66e7f12cface01ce28e4061e84df88a87a295fde
Commit: a6eafec43bac33c40ebdd14f52af931da920421d

2024-01-22 10:39 UTC, Le-Caignec commented on packages/sharing-smart-contract/test/sale.test.js
> +  async function addProtectedDataToCollectionHelper(collectionContract, collectionTokenId, addr) {
Commit: 053e4e3e9211b6e19bd93e9b03ba9b3b4cdb65e2

2024-01-22 18:48 UTC, Le-Caignec commented on packages/sharing-smart-contract/contracts/modules/Sale.sol
> +    }
add two different interfaces

2024-01-30 13:53 UTC, PierreJeanjacquot requested changes

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +            "Collection subscribed"
A bit more explicit
```suggestion
            "Collection has ongoing subscriptions"
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +    // collectionId => subscriber
oudated comment
```suggestion
    // collectionId => subscriptionParams:  SubscriptionParams
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +            "ProtectedData available for subscription"
```suggestion
            "ProtectedData is available in subscription"
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
>      // collectionId => (ProtectedDataTokenId => RentingParams)
outdated comment
```suggestion
    // collectionId => (protectedDataAddress: address => rentingParams: RentingParams)
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +        require(lastRentalExpiration[_protectedData] < block.timestamp, "ProtectedData rented");
not sure
```suggestion
        require(lastRentalExpiration[_protectedData] < block.timestamp, "ProtectedData is currently being rented");
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +    // collectionId => (ProtectedDataTokenId => SellingParam)
outdated comment
```suggestion
    // collectionId => (protectedDataAddress: address => sellingParam: SellingParam)
```

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Collection.sol
should be changed in the future (out of scope)

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Sale.sol
> +        m_collection.adminSwapCollection(_collectionIdFrom, _collectionIdTo, _protectedData);
should change in the future (out of scope)

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Sale.sol
> +        m_collection.adminSafeTransferFrom(_to, _protectedData);
should change in the future (out of scope)

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Subscription.sol
missing modifier `onlyProtectedDataNotForSale(uint256 _collectionId, address _protectedData)` on `setProtectedDataToSubscription`

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Renting.sol
>      ) public onlyProtectedDataInCollection(_collectionId, _protectedData) {
Missing modifier `onlyProtectedDataNotForSale(uint256 _collectionId, address _protectedData)`

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/test/subscription.test.js
>    describe('setProtectedDataToSubscription()', () => {
add test case
- cannot setProtectedDataToSubscription if the protected data is available for sale

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/test/subscription.test.js
> +  describe('removeProtectedDataFromSubscription()', () => {
add test case
- cannot removeProtectedDataFromSubscription if the collection has ongoing subscriptions

2024-01-30 13:53 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/test/renting.test.js
add test case in `setProtectedDataToRenting()`
- cannot setProtectedDataToRenting if the protected data is available for sale

2024-02-01 10:13 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/Store.sol
> +     *                       Saling                                            *
```suggestion
     *                       Selling                                           *
```

2024-02-01 10:16 UTC, PierreJeanjacquot commented on packages/sharing-smart-contract/contracts/modules/Renting.sol
> +    // cannot be rented anymore, pending rental are still valid
```suggestion
    // cannot be rented anymore, ongoing rental are still valid
```

2024-02-01 10:20 UTC, PierreJeanjacquot approved these changes

2024-02-01 10:28 UTC, merged