[SDK] `buyProtectData()` (New PR after module PR got merged)
iExecBlockchainComputing/dataprotector-sdk pull request #174
Opened 2024-02-20 11:00 UTC by cedric25

2024-02-20 17:11 UTC, Le-Caignec requested changes
Good Job, just some comments 👍🏻

2024-02-20 17:11 UTC, Le-Caignec commented on packages/sdk/src/lib/dataProtectorSharing/buyProtectedData.ts
> +        }
you missed the value field : 
```suggestion
        {
           value: // price of the sale
          // TODO: See how we can remove this
          gasLimit: 900_000,
        }
```

2024-02-20 17:11 UTC, Le-Caignec commented on packages/sdk/src/lib/dataProtectorSharing/buyProtectedData.ts
> +        }
idem

2024-02-21 09:13 UTC, cedric25 commented on packages/sdk/src/lib/dataProtectorSharing/buyProtectedData.ts
> +        }
Good catch indeed, thanks

2024-02-21 10:56 UTC, Le-Caignec approved these changes

2024-02-21 10:57 UTC, merged