Feature/local stack tests
iExecBlockchainComputing/dataprotector-sdk pull request #177
Opened 2024-02-26 09:39 UTC by PierreJeanjacquot

2024-02-29 08:22 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - sleep 30
no access to `nc` or `curl` in this image, so the classic open port check is replaced by `sleep 30`

2024-02-29 08:23 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - sleep 30
no access to `nc` or `curl` in this image, so the classic open port check is replaced by `sleep 30`

2024-02-29 08:24 UTC, PierreJeanjacquot commented on packages/sdk/package.json
> +    "start-test-stack": "cd tests && npm run stop-test-stack && node prepare-test-env.js && docker compose up -d"
start and stop scripts (require docker compose)

2024-02-29 08:26 UTC, PierreJeanjacquot commented on packages/sdk/src/dataProtector/processProtectedData.ts
> +    const vProtectedData = addressOrEnsSchema()
this was a bug I found during the development, the protectedData must be specified in processProtectedData (cannot be "any")

2024-02-29 08:28 UTC, PierreJeanjacquot commented on packages/sdk/src/dataProtector/processProtectedData.ts
> +  workerpool,
added `workerpool` option to override the default value as it was not possible (this is required for local testing as we don't control the default pool)

2024-02-29 08:30 UTC, PierreJeanjacquot commented on packages/sdk/src/dataProtector/protectDataObservable.ts
> +            txOptions
txOptions specifies the `gasPrice` we want to inherit it from the `iexec` SDK instance

2024-02-29 08:33 UTC, PierreJeanjacquot commented on packages/sdk/src/utils/validators.ts
> +  string().matches(/^http[s]?:\/\//, '${path} should be a url');
changed the url validation as `yup`'s one does not support `localhost`
the new implementation is not bulletproof but it provides a cheap quick validation

2024-02-29 08:36 UTC, PierreJeanjacquot commented on packages/sdk/tests/e2e/processProtectedData.test.ts
> +    app = appAddress;
create resources on the local stack as the one used before required orders published by third parties on the marketplace (our marketplace instance is empty)

2024-02-29 08:37 UTC, PierreJeanjacquot commented on packages/sdk/tests/prepare-test-env.js
fetch the latest block of the bellecour blockchain to base the local fork

2024-02-29 08:39 UTC, PierreJeanjacquot commented on packages/sdk/tests/test-utils.ts
> +};
create the configuration to connect the local test stack

2024-02-29 08:42 UTC, PierreJeanjacquot commented on packages/subgraph/deployer.Dockerfile
provide a base image for subgraph deployment in local stack, this allow us to cache dependencies installation across multiple reinstantiation of the local stack.

2024-02-29 08:44 UTC, PierreJeanjacquot commented on packages/subgraph/schema.graphql
some v2 code was left, rolled back to what it should be on develop branch (plus `Subscription` is reserved word that prevents to compile)

2024-02-29 16:52 UTC, SeddikBellamine requested changes
Great work !! , i left you some comments, I really like the idea to change the used stack to a local one and not use the real stack.

2024-03-01 08:32 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +    image: ghcr.io/foundry-rs/foundry:latest
I initially started with a hardhat node but had some trouble when all the stack components were connected to it (node becoming unresponsive)
However, I haven't tested hardhat again after stabilizing with foundry anvil.
Another benefit I found after tinkering with foundry was the ability to pass all the fork parameters through cli options, freeing us of the additional burden of maintaining the hardhat docker image with bellecour fork configuration.

2024-03-01 08:47 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - while ! nc -z graphnode-postgres 5432 ; do sleep 1 ; done && echo "graphnode-postgres ready"
I'm aware of `depends_on` and I would like to use it the way I did for the local docker-compose counterpart.
For what I tested drone does not support depends_on X healthy (only depends on X started) which is not enough in this case.
There is probably some room for optimization with depends_on, detached services, and blocking healthchecks steps, but using `depends_on` would convert the whole pipeline into a graph pipeline which is slightly more complex, I'll ask the team for approval :+1:

2024-03-01 08:49 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +    image: graphprotocol/graph-node:v0.27.0
sure, I'll check what is used in production

2024-03-01 10:00 UTC, PierreJeanjacquot commented on packages/sdk/src/dataProtector/processProtectedData.ts
>        appmaxprice: vMaxPrice,
I think you found a bug :bug: :+1:

2024-03-01 10:16 UTC, PierreJeanjacquot commented on packages/sdk/src/dataProtector/processProtectedData.ts
>        appmaxprice: vMaxPrice,
fixed 69a1eb2df073675ee245907fe9b03486c658b829

2024-03-01 10:21 UTC, PierreJeanjacquot commented on packages/sdk/src/utils/validators.ts
> +  string().matches(/^http[s]?:\/\//, '${path} should be a url');
We also need to support drone/docker service name here (ex: `http://graphnode:8000`)
The `/^http[s]?:\/\//` regex is not that big maybe not worth adding in a variable as it is not used elsewhere

2024-03-01 10:27 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +    image: node:18
There is some unclear reason why `18.19` is used in other pipelines probably linked to a bug affecting `tsc`. Changing to 18.19 but only for the sake of having the same version. We need to challenge it.

changed 1aa2e3ad959ae4c8bac6f17e2cbf93cea84b587c

2024-03-01 11:26 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - while ! nc -z graphnode-postgres 5432 ; do sleep 1 ; done && echo "graphnode-postgres ready"
@SeddikBellamine proposal for a graphpipeline https://github.com/iExecBlockchainComputing/dataprotector-sdk/pull/184

2024-03-01 13:10 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +    image: graphprotocol/graph-node:v0.27.0
checked with infra team, the deployed graphnodes uses `0.27.0`, nothing to change on our side IMO.

2024-03-01 13:42 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - sleep 30
changed in #184

2024-03-01 13:42 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - sleep 30
changed in #184

2024-03-01 13:42 UTC, PierreJeanjacquot commented on packages/sdk/.drone.yml
> +      - while ! nc -z graphnode-postgres 5432 ; do sleep 1 ; done && echo "graphnode-postgres ready"
changed in #184

2024-03-05 08:46 UTC, SeddikBellamine approved these changes
LGTM !

2024-03-05 08:49 UTC, SeddikBellamine commented on packages/sdk/.drone.yml
> +    image: graphprotocol/graph-node:v0.27.0
got it

2024-03-05 09:09 UTC, merged