Feature/eslint
iExecBlockchainComputing/dataprotector-sdk pull request #80
Opened 2023-10-13 09:13 UTC by Le-Caignec

2023-10-16 12:13 UTC, PierreJeanjacquot requested changes
see comments

2023-10-16 12:13 UTC, PierreJeanjacquot commented on .eslintrc.json
> +    ],
move this in override for tests

2023-10-16 12:13 UTC, PierreJeanjacquot commented on package.json
useless `--ext .ts` in script `lint`

2023-10-16 13:49 UTC, Le-Caignec commented on package.json
Commit: aa51653d4a02edc86449c4ecbea8586d8c878e64

2023-10-17 08:41 UTC, PierreJeanjacquot approved these changes
:rocket:

2023-10-17 16:37 UTC, merged